openapi: "3.0.0"

info:
    title: URL Shortener API
    description: API for URL shortenet written in Go language

servers:
    - url: http://localhost:9000
      description: Development server[Staging/Production are different from this]

produces:
    - application/json

consumes:
    - application/json

host: localhost:9000

paths:
    /api/create-url:
        post:
            summary: Create Short Url
            description: You can send url and get shortened url
            tags:
                - Url
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateUrl'
                        examples:
                            CreateUrl:
                                value:
                                    original_url: "http://google.com"
            responses:
                '201':
                    description: Created
                    content:
                        application/json:
                            example: "{
                                \"status\": true,
                                \"message\": \"created\",
                                \"errors\": null,
                                \"data\": {
                                    \"original_url\": \"http://google.com\",
                                    \"short_url\": \"localhost:9000/QSsfgcEt\"
                                }
                            }"

                '400':
                    description: bad request
                    content:
                        application/json:
                            example: "{
                                \"status\": false,
                                \"message\": \"bad request\",
                                \"errors\": [
                                  \"OriginalUrl is a required field!\"
                                ],
                                \"data\": null
                            }"

                '500':
                    description: error
                    content:
                        application/json:
                            example: "{
                                \"status\": false,
                                \"message\": \"error\",
                                \"errors\": \"an error has occurred\",
                                \"data\": null
                            }"

    /api/{url_name}:
        get:
            summary: Get url detail
            description: You can send name of shortened url and get url detail like click count
            tags:
                - Url
            parameters:
                - in: path
                  name: url_name
                  schema:
                    type: string
                  required: true
                  description: Shortened url name
            responses:
                '200':
                    description: OK
                    content:
                        application/json:
                            example: "{
                                \"status\": true,
                                \"message\": \"ok\",
                                \"errors\": null,
                                \"data\": {
                                    \"original_url\": \"http://google.com\",
                                    \"click\": 256
                                }
                            }"

                '404':
                    description: Not Found
                    content:
                        application/json:
                            example: "{
                                \"status\": false,
                                \"message\": \"not found\",
                                \"errors\": [
                                  \"url not found\"
                                ],
                                \"data\": null
                            }"

                '500':
                    description: error
                    content:
                        application/json:
                            example: "{
                                \"status\": false,
                                \"message\": \"error\",
                                \"errors\": \"an error has occurred\",
                                \"data\": null
                            }"


components:
    schemas:
        CreateUrl:
            title: Create Url
            type: object
            properties:
                original_url:
                  type: string
            required:
                - original_url